version: "3"

volumes:
  postgres:

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "15432:5432"
